### ISSUE TITLE
POST should be GET in comments for /creatures/:id

### ISSUE THREAD

**Issue by justincastilla** [sf-wdi-24/rails_bog_app#15]
in Part II, Section 7 ([link](https://github.com/sf-wdi-24/rails_bog_app#7-define-a-route-to-show-a-specific-creature))
original text:
```ruby
 # post "/creatures/:id", to: "creatures#show"
```

should be:
```ruby
 # get "/creatures/:id", to: "creatures#show"
```

**Comment by cameronjacoby** [comment]
Fixed - thanks! :smile:
